# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\UI_lab\classes\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


